// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tEST1LINKS() {
    driver.get("http://localhost:8080");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//a[@href=\'/reset\' and text()=\'Reset\']"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST2RESET() {
    driver.get("http://localhost:8080");
    driver.findElement(By.linkText("Reset")).click();
    assertThat(driver.findElement(By.xpath("//ul[@class=\'list-group\']/li[1]")).getText(), is("ID 1. Jennyanydots"));
    assertThat(driver.findElement(By.xpath("//ul[@class=\'list-group\']/li[2]")).getText(), is("ID 2. Old Deuteronomy"));
    assertThat(driver.findElement(By.xpath("//ul[@class=\'list-group\']/li[3]")).getText(), is("ID 3. Mistoffelees"));
  }
  @Test
  public void tEST3CATALOG() {
    driver.get("http://localhost:8080");
    driver.findElement(By.linkText("Catalog")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//ol/li[1]/img[@src=\'/images/cat1.jpg\']"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST4LISTING() {
    driver.get("http://localhost:8080");
    driver.findElement(By.linkText("Catalog")).click();
    {
      List<WebElement> elements = driver.findElements(By.id("cat-id3"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.xpath("//ul[@class=\'list-group\']/li[3]")).getText(), is("ID 3. Mistoffelees"));
  }
  @Test
  public void tEST5RENTACAT() {
    driver.get("http://localhost:8080/rent-a-cat");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[text()=\'Rent\']"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[text()=\'Return\']"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST6RENT() {
    driver.get("http://localhost:8080/rent-a-cat");
    driver.findElement(By.id("rentID")).sendKeys("1");
    driver.findElement(By.xpath("//button[text()=\'Rent\']")).click();
    assertThat(driver.findElement(By.xpath("//ul[@class=\'list-group\']/li[1]")).getText(), is("Rented out"));
    assertThat(driver.findElement(By.xpath("//ul[@class=\'list-group\']/li[2]")).getText(), is("ID 2. Old Deuteronomy"));
    assertThat(driver.findElement(By.xpath("//ul[@class=\'list-group\']/li[3]")).getText(), is("ID 3. Mistoffelees"));
    assertThat(driver.findElement(By.id("rentResult")).getText(), is("Success!"));
  }
  @Test
  public void tEST7RETURN() {
    driver.get("http://localhost:8080/rent-a-cat");
    driver.findElement(By.id("rentID")).sendKeys("1");
    driver.findElement(By.id("returnID")).sendKeys("1");
    driver.findElement(By.xpath("//button[text()=\'Rent\']")).click();
    driver.findElement(By.xpath("//button[text()=\'Return\']")).click();
    assertThat(driver.findElement(By.id("cat-id1")).getText(), is("ID 1. Jennyanydots"));
    assertThat(driver.findElement(By.id("cat-id2")).getText(), is("ID 2. Old Deuteronomy"));
    assertThat(driver.findElement(By.id("cat-id3")).getText(), is("ID 3. Mistoffelees"));
    assertThat(driver.findElement(By.id("returnResult")).getText(), is("Success!"));
  }
  @Test
  public void tEST8FEEDACAT() {
    driver.get("http://localhost:8080/feed-a-cat");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[text()=\"Feed\"]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void tEST9FEED() {
    driver.get("http://localhost:8080/feed-a-cat");
    driver.findElement(By.id("catnips")).sendKeys("6");
    driver.findElement(By.xpath("//button[text()=\"Feed\"]")).click();
    assertThat(driver.findElement(By.xpath("//*[@id=\'feedResult\' and text()=\'Nom, nom, nom.\']")).getText(), is("Nom, nom, nom."));
  }
  @Test
  public void tEST10GREETACAT() {
    driver.get("http://localhost:8080/greet-a-cat");
    assertThat(driver.findElement(By.id("greeting")).getText(), is("Meow!Meow!Meow!"));
  }
  @Test
  public void tEST11GREETACATWITHNAME() {
    driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
    assertThat(driver.findElement(By.id("greeting")).getText(), is("Meow! from Jennyanydots."));
  }
  @Test
  public void dEFECT1FUNFEED() {
    driver.get("http://localhost:8080/feed-a-cat");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    driver.findElement(By.id("catnips")).sendKeys("-3");
    driver.findElement(By.xpath("//button[text()=\"Feed\"]")).click();
    assertThat(driver.findElement(By.xpath("//*[@id=\'feedResult\' and text()=\'Nom, nom, nom.\']")).getText(), is("Cat fight!"));
  }
  @Test
  public void dEFECT2FUNGREETACAT() {
    driver.get("http://localhost:8080/greet-a-cat");
    js.executeScript("document.cookie = \"1=true\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    assertThat(driver.findElement(By.id("greeting")).getText(), is("Meow!Meow!"));
  }
  @Test
  public void dEFECT3FUNGREETACATWITHNAME() {
    driver.get("http://localhost:8080/rent-a-cat");
    driver.findElement(By.id("rentID")).sendKeys("1");
    driver.findElement(By.xpath("//button[text()=\'Rent\']")).click();
    driver.get("https://cs1632.appspot.com//greet-a-cat/Jennyanydots");
    assertThat(driver.findElement(By.xpath("//body")).getText(), is("Jennyanydots is not here.\\\\n"));
  }
}
